import { PluginManifest } from '../types/pluginTypes';

export const CORE_APP_VERSION = '2.4.0';

export const MARKETPLACE_CATALOG: PluginManifest[] = [
  {
    id: 'fujifinder-seo-toolkit',
    name: 'Advanced SEO & Schema Toolkit',
    version: '1.4.2',
    author: {
      name: 'FujiFinder Core Team',
      url: 'https://fujifinder.my.id',
      verified: true,
    },
    description: 'Enterprise-grade JSON-LD camera schema, live SERP keyword density audit, and canonical link automator for tech reviewers.',
    detailedDescription: 'The definitive SEO suite crafted specifically for digital camera reviews and editorial gear comparisons. Automatically injects Schema.org Article, Review, and Product rich snippet metadata with verified star ratings and retailer offer price ranges. Includes a real-time keyword density scanner inside the article editor and Google Search snippet live preview.',
    icon: 'search',
    category: 'SEO',
    compatibility: {
      minAppVersion: '2.0.0',
      testedUpTo: '2.5.0',
    },
    permissions: [
      'articles:read',
      'articles:write',
      'editor_extension',
      'dashboard_widget',
      'settings:read',
      'settings:write',
    ],
    entryPoints: {
      hasDashboardWidget: true,
      hasAdminPage: true,
      hasEditorExtension: true,
      hooks: ['onArticleSave', 'onSchemaGenerate'],
    },
    settingsSchema: [
      {
        id: 'autoSchemaType',
        label: 'Default Schema Strategy',
        description: 'Determines whether articles default to tech reviews or editorial blog posts in Google Search.',
        type: 'select',
        defaultValue: 'auto',
        options: [
          { label: 'Auto-detect (Review if camera linked, else Article)', value: 'auto' },
          { label: 'Force Product Review Schema', value: 'review' },
          { label: 'Force Tech Article Schema', value: 'tech_article' },
        ],
      },
      {
        id: 'keywordDensityThreshold',
        label: 'Target Keyword Density (%)',
        description: 'Ideal focus keyword frequency target for camera deep-dives.',
        type: 'range',
        defaultValue: 1.8,
        min: 0.5,
        max: 4.0,
        step: 0.1,
      },
      {
        id: 'autoCanonicalHost',
        label: 'Production Canonical Domain',
        description: 'Base URL applied to all generated canonical tags.',
        type: 'url',
        defaultValue: 'https://www.fujifinder.my.id',
        placeholder: 'https://www.fujifinder.my.id',
      },
      {
        id: 'enableSerpSimulator',
        label: 'Enable Live SERP Preview in Editor',
        description: 'Shows live mobile and desktop search previews while typing article headlines.',
        type: 'toggle',
        defaultValue: true,
      },
      {
        id: 'gscVerificationMeta',
        label: 'Google Search Console Verification Tag',
        description: 'HTML meta tag content for Google Search Console domain verification.',
        type: 'text',
        defaultValue: '',
        placeholder: 'google-site-verification=abc123...',
      },
    ],
    features: [
      'Dual Article & Camera Review JSON-LD structured data generator',
      'Live keyword density audit with over-optimization warnings',
      'Automated kebab-case slug generator with stop-word filter',
      'Social card OpenGraph & Twitter Card pixel validators',
      'Search Console indexation health dashboard card',
    ],
    changelog: [
      {
        version: '1.4.2',
        date: '2026-09-01',
        changes: [
          'Added instant Schema.org Offer aggregate validation for discontinued cameras',
          'Improved keyword density analyzer to exclude camera EXIF tables from count',
          'Updated canonical tag injector to preserve secure HTTPS domain aliases',
        ],
      },
      {
        version: '1.4.0',
        date: '2026-08-15',
        changes: [
          'Introduced live SERP pixel-width ruler for desktop and mobile displays',
          'Added automatic focus keyword extraction from H1 headlines',
        ],
      },
    ],
    tags: ['seo', 'schema', 'json-ld', 'keywords', 'google-search', 'canonical'],
    rating: 4.9,
    reviewsCount: 142,
    downloadsCount: 18400,
    isOfficial: true,
    lastUpdated: '2026-09-01',
  },
  {
    id: 'fujifinder-analytics-pro',
    name: 'Real-Time Visitor & Affiliate Analytics',
    version: '2.1.0',
    author: {
      name: 'PixelMetrics Lab',
      url: 'https://pixelmetrics.dev',
      verified: true,
    },
    description: 'Privacy-focused editorial traffic analytics, camera interest heatmaps, and affiliate conversion attribution.',
    detailedDescription: 'Provides deep real-time insights into which camera reviews generate the highest reader dwell time and affiliate merchant referrals. Tracks reader scroll depth, outbound merchant clicks (Tokopedia, Shopee, B&H, Amazon), and category popularity without intrusive tracking cookies.',
    icon: 'bar-chart',
    category: 'Analytics',
    compatibility: {
      minAppVersion: '2.1.0',
      testedUpTo: '2.5.0',
    },
    permissions: [
      'analytics:read',
      'analytics:write',
      'articles:read',
      'affiliates:read',
      'dashboard_widget',
    ],
    entryPoints: {
      hasDashboardWidget: true,
      hasAdminPage: true,
      hooks: ['onPageView', 'onAffiliateClick'],
    },
    settingsSchema: [
      {
        id: 'trackingMode',
        label: 'Privacy Tracking Mode',
        description: 'Select level of IP masking and analytics anonymization.',
        type: 'select',
        defaultValue: 'strict_privacy',
        options: [
          { label: 'Strict Privacy (Zero-Cookie, Fully Masked IP)', value: 'strict_privacy' },
          { label: 'Standard Session Dwell Tracking', value: 'standard' },
        ],
      },
      {
        id: 'excludeAdminVisits',
        label: 'Exclude Admin Visits',
        description: 'Ignore pageviews originating from logged-in editors.',
        type: 'toggle',
        defaultValue: true,
      },
      {
        id: 'liveRefreshInterval',
        label: 'Dashboard Live Refresh Interval',
        description: 'Frequency of real-time widget updates in seconds.',
        type: 'select',
        defaultValue: '30',
        options: [
          { label: '15 seconds (High Frequency)', value: '15' },
          { label: '30 seconds (Recommended)', value: '30' },
          { label: '60 seconds (Low Bandwidth)', value: '60' },
        ],
      },
      {
        id: 'goalConversionValue',
        label: 'Estimated Value Per Affiliate Click ($)',
        description: 'Used to estimate potential referral earnings.',
        type: 'number',
        defaultValue: 1.25,
        min: 0,
        max: 50,
      },
    ],
    features: [
      'Real-time reader activity feed with dwell-time meters',
      'Retailer referral conversion breakdown (Tokopedia, B&H, Shopee)',
      'Most compared camera combinations analytics',
      'Zero external trackers; GDPR and CCPA compliant by design',
    ],
    changelog: [
      {
        version: '2.1.0',
        date: '2026-08-28',
        changes: [
          'Added real-time affiliate click stream with merchant badges',
          'Enhanced bounce rate algorithm based on reading progress',
        ],
      },
    ],
    tags: ['analytics', 'privacy', 'traffic', 'conversions', 'affiliate-tracking'],
    rating: 4.8,
    reviewsCount: 98,
    downloadsCount: 12900,
    isOfficial: true,
    lastUpdated: '2026-08-28',
  },
  {
    id: 'fujifinder-affiliate-cloaker',
    name: 'Affiliate Deep Link Cloaker & Retailer Rotator',
    version: '1.2.0',
    author: {
      name: 'MonetizeGear',
      url: 'https://monetizegear.io',
      verified: true,
    },
    description: 'Clean branded redirect URLs (/go/camera-name), automatic UTM injection, and unmonetized mention scanner.',
    detailedDescription: 'Turn ugly affiliate tracking links into trustworthy, branded redirection URLs like https://www.fujifinder.my.id/go/x100vi. Scans your draft articles for unlinked camera model names and suggests one-click affiliate link insertions.',
    icon: 'link',
    category: 'Affiliate Marketing',
    compatibility: {
      minAppVersion: '2.0.0',
      testedUpTo: '2.5.0',
    },
    permissions: [
      'affiliates:read',
      'affiliates:write',
      'articles:read',
      'editor_extension',
      'dashboard_widget',
    ],
    entryPoints: {
      hasDashboardWidget: true,
      hasAdminPage: true,
      hasEditorExtension: true,
      hooks: ['onAffiliateClick', 'onArticleEditorLoad'],
    },
    settingsSchema: [
      {
        id: 'cloakPrefix',
        label: 'Redirect Link Prefix',
        description: 'URL path prefix for cloaked merchant links.',
        type: 'text',
        defaultValue: '/go/',
        placeholder: '/go/',
        required: true,
      },
      {
        id: 'utmSourceDefault',
        label: 'Default UTM Campaign Source',
        description: 'Appended automatically to outbound retailer destinations.',
        type: 'text',
        defaultValue: 'fujifinder_editorial',
        placeholder: 'fujifinder_editorial',
      },
      {
        id: 'autoSponsoredRel',
        label: 'Enforce rel="sponsored noopener" on External Links',
        description: 'Ensures full compliance with Google Search affiliate link policies.',
        type: 'toggle',
        defaultValue: true,
      },
      {
        id: 'unmonetizedAlertBadge',
        label: 'Highlight Unmonetized Camera Mentions in Editor',
        description: 'Displays a notification in draft articles when high-demand cameras lack buy links.',
        type: 'toggle',
        defaultValue: true,
      },
    ],
    features: [
      'Branded clean link redirection (/go/product-slug)',
      'Automatic UTM campaign parameter tagging',
      'Unlinked camera mention scanner inside article editor',
      'Compliance enforcement for rel="sponsored nofollow"',
    ],
    changelog: [
      {
        version: '1.2.0',
        date: '2026-08-20',
        changes: [
          'Added automatic fallback retailer routing if prime merchant is out of stock',
          'Integrated unmonetized camera scanner drawer into CMS editor',
        ],
      },
    ],
    tags: ['affiliate', 'monetization', 'cloaking', 'utm-tags', 'tokopedia', 'shopee'],
    rating: 4.9,
    reviewsCount: 114,
    downloadsCount: 15700,
    isOfficial: true,
    lastUpdated: '2026-08-20',
  },
  {
    id: 'fujifinder-image-optimizer',
    name: 'WebP & Retina Image Optimizer',
    version: '1.0.5',
    author: {
      name: 'LensSharp Engineering',
      url: 'https://lenssharp.photos',
      verified: true,
    },
    description: 'Automatic image compression, responsive srcset generator, EXIF preview, and lazy loading booster for high-res camera samples.',
    detailedDescription: 'Photography reviews require stunning full-resolution sample photos, but heavy uncompressed JPEGs hurt Google PageSpeed. This plugin automates progressive image loading, WebP compression, lazy-loading thresholds, and cleans unnecessary camera EXIF blobs while preserving essential camera metadata (ISO, Shutter, Aperture).',
    icon: 'image',
    category: 'Image Optimization',
    compatibility: {
      minAppVersion: '2.0.0',
      testedUpTo: '2.5.0',
    },
    permissions: [
      'media:read',
      'media:write',
      'dashboard_widget',
    ],
    entryPoints: {
      hasDashboardWidget: true,
      hasAdminPage: true,
    },
    settingsSchema: [
      {
        id: 'webpQuality',
        label: 'WebP Compression Quality (%)',
        description: 'Balance between visual sharpness and file size reduction.',
        type: 'range',
        defaultValue: 85,
        min: 60,
        max: 98,
        step: 1,
      },
      {
        id: 'enableLazyThreshold',
        label: 'Aggressive Lazy Loading',
        description: 'Defer off-screen camera test photos until reader scrolls within 200px.',
        type: 'toggle',
        defaultValue: true,
      },
      {
        id: 'preserveExifGearTags',
        label: 'Preserve Aperture, Shutter & ISO EXIF in Captions',
        description: 'Extracts camera shot parameters for display in photo captions.',
        type: 'toggle',
        defaultValue: true,
      },
      {
        id: 'cdnOptimizationProxy',
        label: 'Fast Image Delivery CDN Proxy',
        description: 'Route external Unsplash and camera photos through high-speed caching edge.',
        type: 'select',
        defaultValue: 'unsplash_edge',
        options: [
          { label: 'Unsplash & Cloudflare Edge (Optimized)', value: 'unsplash_edge' },
          { label: 'Direct Source Origin', value: 'direct' },
        ],
      },
    ],
    features: [
      'Automated WebP conversion reducing image sizes by up to 68%',
      'Preserves crucial photo EXIF data for lens & camera reviews',
      'Responsive srcset generation for mobile vs 4K Retina displays',
      'Admin media library storage savings report',
    ],
    changelog: [
      {
        version: '1.0.5',
        date: '2026-08-10',
        changes: [
          'Added automatic WebP alt-tag accessibility audit',
          'Improved client-side image compression buffer speed',
        ],
      },
    ],
    tags: ['image', 'webp', 'retina', 'compression', 'pagespeed', 'exif'],
    rating: 4.7,
    reviewsCount: 65,
    downloadsCount: 9400,
    isOfficial: false,
    lastUpdated: '2026-08-10',
  },
  {
    id: 'fujifinder-social-share',
    name: 'Editorial Social Share & OpenGraph Automator',
    version: '1.3.1',
    author: {
      name: 'ViralShutter Media',
      url: 'https://viralshutter.app',
      verified: true,
    },
    description: 'Elegant floating editorial share bar, Twitter/X thread previews, WhatsApp quick-share, and one-click quote sharing.',
    detailedDescription: 'Increases article viral reach among camera enthusiasts. Renders a tasteful floating share bar along the side of long-form reviews with direct share intents for Twitter/X, WhatsApp, Threads, Pinterest, and Reddit. Includes a one-click copy URL button with haptic feedback.',
    icon: 'share-2',
    category: 'Social Media',
    compatibility: {
      minAppVersion: '2.0.0',
      testedUpTo: '2.5.0',
    },
    permissions: [
      'articles:read',
      'frontend_injection',
      'settings:read',
    ],
    entryPoints: {
      hasFrontendComponent: true,
      hasAdminPage: true,
    },
    settingsSchema: [
      {
        id: 'enableFloatingBar',
        label: 'Enable Floating Social Bar on Articles',
        description: 'Displays a sticky share widget on the left margin of desktop screens.',
        type: 'toggle',
        defaultValue: true,
      },
      {
        id: 'socialTwitterHandle',
        label: 'Twitter / X Editorial Handle',
        description: 'Appended as via @Handle on tweets.',
        type: 'text',
        defaultValue: 'FujiFinder',
        placeholder: 'FujiFinder',
      },
      {
        id: 'activeNetworks',
        label: 'Active Sharing Channels',
        description: 'Choose which platforms appear in the reader share toolbar.',
        type: 'select',
        defaultValue: 'standard',
        options: [
          { label: 'All Channels (X, WhatsApp, Pinterest, Copy Link)', value: 'standard' },
          { label: 'Minimalist (X, WhatsApp, Copy Link)', value: 'minimal' },
        ],
      },
      {
        id: 'accentColor',
        label: 'Widget Brand Accent Color',
        description: 'Accent highlight for active share icons.',
        type: 'color',
        defaultValue: '#1A1A1A',
      },
    ],
    features: [
      'Floating editorial share bar with high-contrast minimalist styling',
      'Direct WhatsApp and X share integration with pre-filled camera titles',
      'One-click URL copy with animated confirmation toast',
      'Native OpenGraph image preview generator inside admin editor',
    ],
    changelog: [
      {
        version: '1.3.1',
        date: '2026-08-25',
        changes: [
          'Added direct WhatsApp Web and Mobile deep linking',
          'Fine-tuned floating position so it never overlaps comparison tables',
        ],
      },
    ],
    tags: ['social', 'sharing', 'twitter', 'whatsapp', 'floating-bar', 'opengraph'],
    rating: 4.8,
    reviewsCount: 83,
    downloadsCount: 11200,
    isOfficial: false,
    lastUpdated: '2026-08-25',
  },
  // Additional Marketplace Discoverable Plugins
  {
    id: 'fujifinder-ai-writer',
    name: 'AI Camera Review Assistant & Spec Parser',
    version: '1.1.0',
    author: {
      name: 'DeepLens AI',
      url: 'https://deeplens.ai',
      verified: true,
    },
    description: 'Generates objective camera pros & cons, summarizes lab sharpness measurements, and drafts comparison verdict blocks.',
    detailedDescription: 'Integrates Gemini directly into the FujiFinder article editor. Instantly drafts balanced comparison verdicts between two cameras, extracts pros & cons from testing notes, and formats technical camera specs into clean markdown comparison tables.',
    icon: 'sparkles',
    category: 'AI Tools',
    compatibility: {
      minAppVersion: '2.1.0',
      testedUpTo: '2.5.0',
    },
    permissions: [
      'articles:read',
      'articles:write',
      'products:read',
      'editor_extension',
      'external_api',
    ],
    entryPoints: {
      hasEditorExtension: true,
      hasAdminPage: true,
    },
    settingsSchema: [
      {
        id: 'aiWritingTone',
        label: 'Editorial Tone',
        description: 'Tone of voice for auto-generated camera summaries.',
        type: 'select',
        defaultValue: 'objective_technical',
        options: [
          { label: 'Objective & Technical (DPReview style)', value: 'objective_technical' },
          { label: 'Warm & Narrative (Storyteller)', value: 'warm_narrative' },
          { label: 'Concise & Punchy (Buyer’s Quick Guide)', value: 'concise' },
        ],
      },
      {
        id: 'autoProsConsCount',
        label: 'Number of Pros & Cons to Generate',
        description: 'Default bullet points generated per camera breakdown.',
        type: 'number',
        defaultValue: 4,
        min: 2,
        max: 8,
      },
    ],
    features: [
      'Instant camera comparison matrix generator',
      'Automated sensor & lens spec comparison draft',
      'Field-testing bullet point summarizer',
    ],
    changelog: [
      {
        version: '1.1.0',
        date: '2026-08-18',
        changes: ['Added support for hybrid video codec comparisons'],
      },
    ],
    tags: ['ai', 'gemini', 'writing-assistant', 'specs', 'comparison'],
    rating: 4.9,
    reviewsCount: 47,
    downloadsCount: 6800,
    isOfficial: false,
    lastUpdated: '2026-08-18',
  },
  {
    id: 'fujifinder-audit-security',
    name: 'Admin Shield & Two-Factor Auth',
    version: '1.0.8',
    author: {
      name: 'SafePortal Security',
      url: 'https://safeportal.net',
      verified: true,
    },
    description: 'Enforce two-factor authentication, monitor suspicious admin logins, and implement IP rate-limiting protection.',
    detailedDescription: 'Protects the FujiFinder CMS dashboard against unauthorized account takeovers. Includes login attempt audit logging, session timeout controls, and automated IP lockout after consecutive failed attempts.',
    icon: 'shield',
    category: 'Security',
    compatibility: {
      minAppVersion: '2.0.0',
      testedUpTo: '2.5.0',
    },
    permissions: [
      'settings:read',
      'settings:write',
      'dashboard_widget',
    ],
    entryPoints: {
      hasDashboardWidget: true,
      hasAdminPage: true,
    },
    settingsSchema: [
      {
        id: 'maxFailedAttempts',
        label: 'Max Failed Login Attempts Before Lockout',
        description: 'Number of wrong passwords allowed before temporary lockout.',
        type: 'number',
        defaultValue: 5,
        min: 3,
        max: 10,
      },
      {
        id: 'autoSessionTimeout',
        label: 'Admin Inactivity Session Timeout (Minutes)',
        description: 'Auto log-out idle administrators after this duration.',
        type: 'number',
        defaultValue: 60,
        min: 15,
        max: 480,
      },
    ],
    features: [
      'Brute-force protection with temporary IP bans',
      'Admin login activity history with geo-location detection',
      'Strict session timeout policies',
    ],
    changelog: [
      {
        version: '1.0.8',
        date: '2026-07-29',
        changes: ['Enhanced local storage encryption for authentication tokens'],
      },
    ],
    tags: ['security', '2fa', 'protection', 'audit-log', 'lockout'],
    rating: 4.8,
    reviewsCount: 39,
    downloadsCount: 5200,
    isOfficial: false,
    lastUpdated: '2026-07-29',
  },
  {
    id: 'fujifinder-newsletter-sync',
    name: 'Reader Newsletter & Email Campaign Syncer',
    version: '1.3.0',
    author: {
      name: 'SendCraft HQ',
      url: 'https://sendcraft.io',
      verified: true,
    },
    description: 'Collect reader emails on camera guides and automatically sync subscriber lists with Mailchimp, ConvertKit, or Brevo.',
    detailedDescription: 'Monetize high-intent camera buyers through targeted email roundups. Embeds responsive newsletter capture boxes at the end of camera guides and syncs subscribers directly with your preferred email marketing service.',
    icon: 'mail',
    category: 'Email Marketing',
    compatibility: {
      minAppVersion: '2.0.0',
      testedUpTo: '2.5.0',
    },
    permissions: [
      'articles:read',
      'frontend_injection',
      'external_api',
    ],
    entryPoints: {
      hasFrontendComponent: true,
      hasAdminPage: true,
    },
    settingsSchema: [
      {
        id: 'provider',
        label: 'Email Marketing Service',
        description: 'Select your newsletter platform.',
        type: 'select',
        defaultValue: 'mailchimp',
        options: [
          { label: 'Mailchimp', value: 'mailchimp' },
          { label: 'ConvertKit / Kit', value: 'convertkit' },
          { label: 'Brevo (Sendinblue)', value: 'brevo' },
          { label: 'Local CSV List Only', value: 'local' },
        ],
      },
      {
        id: 'newsletterHeadline',
        label: 'Signup Box Title',
        description: 'Header displayed to readers above the email input.',
        type: 'text',
        defaultValue: 'Get Weekly Camera Deals & Field Testing Notes',
        placeholder: 'Get Weekly Camera Deals & Field Testing Notes',
      },
    ],
    features: [
      'Direct API synchronization with major email marketing providers',
      'High-converting editorial email signup forms',
      'Downloadable CSV subscriber export',
    ],
    changelog: [
      {
        version: '1.3.0',
        date: '2026-08-05',
        changes: ['Added Kit (ConvertKit) v4 API authentication'],
      },
    ],
    tags: ['newsletter', 'email', 'mailchimp', 'subscribers', 'lead-gen'],
    rating: 4.6,
    reviewsCount: 31,
    downloadsCount: 4100,
    isOfficial: false,
    lastUpdated: '2026-08-05',
  },
  {
    id: 'fujifinder-speed-cache',
    name: 'Instant Preload & Cache Accelerator',
    version: '2.0.1',
    author: {
      name: 'TurboEdge Dev',
      url: 'https://turboedge.dev',
      verified: true,
    },
    description: 'Predictive hover preloading for camera reviews and local asset memory caching for instant page transitions.',
    detailedDescription: 'Delivers instantaneous page transitions when readers hover over camera cards and review links. Pre-fetches article JSON payloads and images in the background, slashing page load times to under 50ms.',
    icon: 'zap',
    category: 'Performance',
    compatibility: {
      minAppVersion: '2.0.0',
      testedUpTo: '2.5.0',
    },
    permissions: [
      'articles:read',
      'products:read',
      'frontend_injection',
    ],
    entryPoints: {
      hasFrontendComponent: true,
      hasAdminPage: true,
    },
    settingsSchema: [
      {
        id: 'hoverPreloadDelay',
        label: 'Hover Preload Delay (ms)',
        description: 'How long user must hover over a link before preloading begins.',
        type: 'number',
        defaultValue: 65,
        min: 20,
        max: 300,
      },
      {
        id: 'preloadTopArticles',
        label: 'Preload Top 3 Trending Guides on Homepage',
        description: 'Pre-cache the most popular reviews immediately upon landing.',
        type: 'toggle',
        defaultValue: true,
      },
    ],
    features: [
      'Hover-intent predictive article preloading',
      'Memory cache for instant backwards/forwards navigation',
      'Saves mobile bandwidth by skipping preloads on low-data connections',
    ],
    changelog: [
      {
        version: '2.0.1',
        date: '2026-08-22',
        changes: ['Added battery-saver detection to disable preloading on low power'],
      },
    ],
    tags: ['performance', 'speed', 'cache', 'preload', 'instant-page'],
    rating: 4.9,
    reviewsCount: 58,
    downloadsCount: 8900,
    isOfficial: false,
    lastUpdated: '2026-08-22',
  },
];

// Initial pre-installed plugins (to demonstrate a working, configured plugin system out of the box)
export const INITIAL_INSTALLED_PLUGINS_DATA = [
  {
    manifest: {
      ...MARKETPLACE_CATALOG[0], // SEO Toolkit (version 1.4.0 installed, update to 1.4.2 available in marketplace!)
      version: '1.4.0',
    },
    status: 'active' as const,
    installedAt: '2026-08-15T09:30:00.000Z',
    updatedAt: '2026-08-15T09:30:00.000Z',
    settings: {
      autoSchemaType: 'auto',
      keywordDensityThreshold: 1.8,
      autoCanonicalHost: 'https://www.fujifinder.my.id',
      enableSerpSimulator: true,
      gscVerificationMeta: 'google-site-verification=FF_PROD_VERIFIED_2026',
    },
    approvedPermissions: MARKETPLACE_CATALOG[0].permissions,
    source: 'marketplace' as const,
  },
  {
    manifest: MARKETPLACE_CATALOG[1], // Analytics Pro (2.1.0)
    status: 'active' as const,
    installedAt: '2026-08-20T14:15:00.000Z',
    updatedAt: '2026-08-28T11:00:00.000Z',
    settings: {
      trackingMode: 'strict_privacy',
      excludeAdminVisits: true,
      liveRefreshInterval: '30',
      goalConversionValue: 1.25,
    },
    approvedPermissions: MARKETPLACE_CATALOG[1].permissions,
    source: 'marketplace' as const,
  },
  {
    manifest: MARKETPLACE_CATALOG[2], // Affiliate Cloaker (1.2.0)
    status: 'active' as const,
    installedAt: '2026-08-22T08:45:00.000Z',
    updatedAt: '2026-08-22T08:45:00.000Z',
    settings: {
      cloakPrefix: '/go/',
      utmSourceDefault: 'fujifinder_review',
      autoSponsoredRel: true,
      unmonetizedAlertBadge: true,
    },
    approvedPermissions: MARKETPLACE_CATALOG[2].permissions,
    source: 'marketplace' as const,
  },
  {
    manifest: MARKETPLACE_CATALOG[3], // Image Optimizer (1.0.5)
    status: 'active' as const,
    installedAt: '2026-08-24T16:20:00.000Z',
    updatedAt: '2026-08-24T16:20:00.000Z',
    settings: {
      webpQuality: 85,
      enableLazyThreshold: true,
      preserveExifGearTags: true,
      cdnOptimizationProxy: 'unsplash_edge',
    },
    approvedPermissions: MARKETPLACE_CATALOG[3].permissions,
    source: 'marketplace' as const,
  },
  {
    manifest: MARKETPLACE_CATALOG[4], // Social Share (1.3.1)
    status: 'active' as const,
    installedAt: '2026-08-26T10:00:00.000Z',
    updatedAt: '2026-08-26T10:00:00.000Z',
    settings: {
      enableFloatingBar: true,
      socialTwitterHandle: 'FujiFinder',
      activeNetworks: 'standard',
      accentColor: '#1A1A1A',
    },
    approvedPermissions: MARKETPLACE_CATALOG[4].permissions,
    source: 'marketplace' as const,
  },
];
